-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('ASSIGNMENT_PROGRAM', 'ASSIGNMENT_BENEFICIARY', 'REPLACEMENT_REQUESTED', 'REPLACEMENT_DECIDED', 'EXPENSE_REVIEWED', 'OUTCOME_REVIEWED', 'SYSTEM') NOT NULL;
